### ISSUE TITLE
Check box colors

### ISSUE THREAD

**Issue by 0xcpu** [techbliss/x64dbg_solarized_dark_mod#1]
I've installed the fonts, copied style.css as mentioned in x64dbg wiki and changed colors in my .ini file.

I have observed an issue with the color of the check boxes. Is it just for me?
![check-buttons](https://cloud.githubusercontent.com/assets/2598963/20728665/6d7080a8-b687-11e6-9a33-7b7d14eaf9b3.png)

Thanks a lot for your great work!

**Comment by techbliss** [comment]
I would need to update some icons colors, thx for bringing it to my attention.

**Comment by techbliss** [comment]
did you put the icon folder in root folder, i have no issues when clicking checkboxes.

![iii](https://cloud.githubusercontent.com/assets/3592375/20742170/0beb2eee-b6cf-11e6-9e61-82104860c2c7.png)

**Comment by 0xcpu** [comment]
No, initially I didn't. 

Now it's working as intended, I'm sorry.

Thank you!
